services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Mapeando a porta 80 do contêiner para a 3000 no host
    environment:
      - CHOKIDAR_USEPOLLING=true