apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: LoadBalancer  # Isso vai expor sua aplicação com um IP externo
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80         # Porta externa que será exposta
    targetPort: 80   # Porta no container
