export { default as LoginPage } from './LoginPage/Index';
export { default as UserRegistrationPage } from './UserRegistrationPage/Index';
export { default as HomePage } from './HomePage/Index';
export { default as SalePage} from './SalePage/Index';
export { default as ProductPage } from './ProductPage/Index';
export { default as ProductRegistrationPage} from "./ProductRegistrationPage/Index";
export { default as CashRegisterPage } from "./CashRegisterPage/Index";
export { default as CashRegisterMovementsPage } from "./CashRegisterMovementsPage/Index";
export { default as CashRegisterClosingPage } from "./CashRegisterClosingPage/Index";
export { default as SalesFilterPage} from "./SaleFIlterPage/Index";