name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job de Build da Imagem do Frontend
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/finance-manager-437520/frontend -f Dockerfile .
          docker push gcr.io/finance-manager-437520/frontend

  # Job para aplicar os manifestos Kubernetes do Frontend
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: finance-manager-437520
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure kubectl with GKE
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials autopilot-cluster-1 --region southamerica-east1

      - name: Apply Frontend service
        run: kubectl apply -f k8s/frontend-service.yaml

      - name: Apply Frontend deployment
        run: kubectl apply -f k8s/frontend-deployment.yaml
